version: "1"

capabilities:
  - contract_id: "abesh:trigger:gorilla"
    values:
      host: "0.0.0.0"
      port: "8080"
      default_request_timeout: "5s"

  - contract_id: "abesh:ex_echo"
    values:
      key1: "test1"
      key2: "test2"

triggers:
  - trigger: "abesh:httpserver"
    trigger_values:
      method: "GET"
      path: "/default"
    service: "abesh:ex_echo"

start:
  - "abesh:httpserver"
